version: "3.3"
services:
  nginx:
    ports:
      - "5000:80"
  chat-api:
    build:
      context: .
      args:
        NODE_ENV: production
    deploy:
      replicas: 8
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 15s
        failure_action: rollback
    environment:
      - NODE_ENV=production
    command: node server.js
